version: "3"
services:
  grader:
    image: palyvos/debs-2020-challenge-grader
    container_name: benchmark-grader
    restart: always
    volumes:
      - ./dataset:/dataset
    ports:
      - 8080:80
    networks:
          - bench

  solution:
    container_name: solution-app
    build:
      context: .
      dockerfile: Dockerfile.solution
    environment:
      BENCHMARK_SYSTEM_URL: 'grader'
    depends_on:
      - grader
    networks:
          - bench

networks:
    bench: {}
